apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: talknotesback
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: talknotesback
    spec:
      hostname: talknotesback
      containers:
        - name: talknotesback
          image: kubecontainerregistry.azurecr.io/scaled/talknotesback
          ports:
          - containerPort: 8082
            name: talknotesback
      imagePullSecrets:
        - name: regsecret
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: talknotesback
spec:
  ports:
  - port: 8082
  selector:
    app: talknotesback
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: talk-notes-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: talk-notes-front
    spec:
      containers:
        - name: talk-notes-front
          image: kubecontainerregistry.azurecr.io/scaled/talknotesfront
      imagePullSecrets:
        - name: regsecret
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: talk-notes-front
spec:
  type: LoadBalancer
  ports:
  - port: 8081
  selector:
    app: talk-notes-front
