apiVersion: v1
kind: Pod
metadata:
  name: talk-notes-back
spec:
  containers:
    - name: talk-notes-back
      image: kubecontainerregistry.azurecr.io/scaled/talknotesback
  imagePullSecrets:
    - name: regsecret
  nodeSelector:
    beta.kubernetes.io/os: windows
--- 
apiVersion: v1
kind: Pod
metadata:
  name: talk-notes-front
spec:
  containers:
    - name: talk-notes-front
      image: kubecontainerregistry.azurecr.io/scaled/talknotesfront
  imagePullSecrets:
    - name: regsecret
  nodeSelector:
    beta.kubernetes.io/os: windows
 
